### ISSUE TITLE
Error: Did not check() all arguments during publisher 'stream-*********'

### ISSUE THREAD

**Issue by wei170** [elmarti/meteor-video-chat#74] opened 2018-02-21 17:22 UTC
![image](https://user-images.githubusercontent.com/13220740/36494800-2a99b84a-1701-11e8-9162-5600ee09bdde.png)

I had this error, when the target user confirmed the call. The caller connected to the iceServers and rendered the video and audio functionality successfully. But target user did not, and give this error in the server. I can't figure out where trigger this. Maybe it is not caused by this package. Did anyone have this similar problem?

**Comment by wei170** [comment] 2018-02-21 17:43
I had the `audit-argument-checks` meteor package. After I removed it, the video chat worked just fine. @elmarti If you have some extra time, would you mind to take a look at all publishers and `check()` every argument? Thank you for this awesome package and examples!

**Comment by elmarti** [comment] 2018-02-21 21:37
Thanks for the feedback, it looks like there's a bit of inconsistency in the checks so I can update them all on this side.

I'll also have to check that this issue doesn't exist in the dependencies as well.

**Comment by elmarti** [comment] 2018-02-21 21:40
The streaming package appears to be using it  https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/server/server.js

**Comment by elmarti** [comment] 2018-02-21 21:42
As does the user-status package. Hoping to remove these eventually, but not within the scope of this issue https://github.com/mizzao/meteor-user-status/blob/master/status.coffee

**Comment by elmarti** [comment] 2018-02-21 21:59
I've added one check to `meteor-video-chat` however it looks like it's an issue with the streamer package, as there is an optional parameter, for which there is no check https://github.com/RocketChat/meteor-streamer/blob/6942960871436d855b57832bee6179cedf2dc324/packages/rocketchat-streamer/server/server.js#L263

I'll see what I can do, worst case scenario I'll have to look to switching it out

**Comment by elmarti** [comment] 2018-02-21 22:00
https://github.com/elmarti/meteor-video-chat/tree/74-add-check-sanitize-for-all

**Comment by elmarti** [comment] 2018-02-21 22:14
Ok, found the root cause, there is currently a pull request open on that repo, if I don't hear back by tomorrow i'll find a way around it https://github.com/RocketChat/meteor-streamer/issues/29

**Comment by maxnowack** [comment] 2018-02-22 09:38
@elmarti here is my workaround for the root cause until rocketchat/meteor-streamer#28 gets merged: https://gist.github.com/maxnowack/9ef59ab12c49699c861e7069a495a49a

**Comment by elmarti** [comment] 2018-02-22 11:12
Great, thanks @maxnowack

**Comment by elmarti** [comment] 2018-02-22 12:38
PR has been merged, just awaiting publication

**Closed** 2018-02-22 13:29 UTC
Labels: in progress

**Comment by elmarti** [comment] 2018-02-22 20:42
Hi, v`2.1.4` now released https://atmospherejs.com/elmarti/video-chat
